# fly.toml app configuration file generated for lcbot on 2024-02-25T23:23:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lcbot'
primary_region = 'ewr'

[build]
  builder = 'paketobuildpacks/builder:base'

[deploy]
  strategy = 'bluegreen'

[processes]
  worker = "python index.py"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['worker']

[[http_service.checks]]
  grace_period = "10s"
  protocol = "http"  # Because you're using Flask
  port = 5000  # Assuming your Flask app runs on port 5000 (change if different)
  path = "/health"  # The endpoint defined in your Flask app
  interval = "15s"  # Check the health every 15 seconds
  timeout = "2s"  # Timeout after 2 seconds of no response
  restart_limit = 0  # Restart the service (i.e., your bot) if unhealthy

[[vm]]
  size = 'shared-cpu-1x'

