# fly.toml app configuration file generated for lcbot on 2024-02-25T23:23:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lcbot'
primary_region = 'ewr'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

    [[services.ports]]
      handlers = ["http"]
      port = 80
      force_https = true
    


[[vm]]
  size = 'shared-cpu-1x'

